[pytest]
addopts = --reruns 1 --reruns-delay 2
testpaths = case
python_files = test_*.py
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = True
markers =
    order-scope : session
    no_cookie: 쿠키 없이 테스트 실행
    gw0: gw0 worker에서만 실행
